apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: video-service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: video-service
    spec:
      containers:
      - image: public.ecr.aws/s0p6q3j7/video-service:v1.0.6-a4009f8
        imagePullPolicy: Always
        name: video-service
        ports:
        - containerPort: 5002
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: DATABASE_URL
            value: postgres://postgres:Mayhabuoi123@database-1.cdqce6siqwx7.ap-southeast-1.rds.amazonaws.com:5432/devtube
          - name: AWS_BUCKET_NAME
            value: devtube-video
          - name: AWS_REGION
            value: ap-southeast-1
          - name: AWS_ROLE_ARN
            value: arn:aws:iam::564439693649:role/GoogleOIDC-S3Access
          - name: MAX_FILE_SIZE
            value: '5242880'
          - name: ALLOWED_FILE_TYPES
            value: mp4,mov,webm,avi,mkv
          - name: MULTIPART_THRESHOLD
            value: '5242880'
          - name: PART_SIZE
            value: '5242880'
          - name: PRESIGNED_URL_EXPIRY
            value: '3600'
          - name: AUTH_SERVICE_URL
            value: auth-service:80
          - name: VIDEO_SERVICE_URL
            value: video-service:80

---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: video-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-service-deployment
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 2
        periodSeconds: 10
      selectPolicy: Max
