---
apiVersion: v1
kind: Namespace
metadata:
  name: devtube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devtube
  name: video-service-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: video-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: video-service
    spec:
      containers:
      - image: public.ecr.aws/s0p6q3j7/video-service:v0.0.4-76ad641
        imagePullPolicy: Always
        name: video-service
        ports:
        - containerPort: 5002
        env:
          - name: DATABASE_URL
            value: postgres://postgres:Mayhabuoi123@database-1.cdqce6siqwx7.ap-southeast-1.rds.amazonaws.com:5432/devtube
          - name: AWS_BUCKET_NAME
            value: devtube-video
          - name: AWS_REGION
            value: ap-southeast-1
          - name: ROLE_ARN
            value: arn:aws:iam::564439693649:role/GoogleOIDC-S3Access
          - name: MAX_FILE_SIZE
            value: '5242880'
          - name: ALLOWED_FILE_TYPES
            value: mp4,mov,webm,avi,mkv
          - name: MULTIPART_THRESHOLD
            value: '5242880'
          - name: PART_SIZE
            value: '5242880'
          - name: PRESIGNED_URL_EXPIRY
            value: '3600'
          - name: AUTH_SERVICE_URL
            value: http://auth-service:80
          - name: VIDEO_SERVICE_URL
            value: http://video-service:80

---
apiVersion: v1
kind: Service
metadata:
  namespace: devtube
  name: video-service
spec:
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: video-service
