apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
    spec:
      containers:
      - image: public.ecr.aws/s0p6q3j7/api-gateway:v1.0.11-742bf38
        imagePullPolicy: Always
        name: api-gateway
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: DATABASE_URL
            value: postgres://postgres:Mayhabuoi123@database-1.cdqce6siqwx7.ap-southeast-1.rds.amazonaws.com:5432/devtube?pool_timeout=0
          - name: GOOGLE_CLIENT_ID
            value: 176483374184-ver0sc6l2iguv2kbfklcqsqr5o34ensh.apps.googleusercontent.com
          - name: GOOGLE_CLIENT_SECRET
            value: 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
          - name: GOOGLE_REDIRECT_URL
            value: https://devtube-team.netlify.app
          - name: GRANT_TYPE
            value: authorization_code
          - name: JWT_ACCESS_SECRET
            value: 15eaf6493ea1153cba48493330eee2e7563076daa0ffd655e6d087f77ef59a83b7ee020ee9e0c7d6972d2eb88e531a67bcf5acc8288c738c343f49a89053b512127495aa0e1286b3c7e811346953c1dbb26aa545ac06205ed5ed421e59ed941a928950b708c975dbd1d32f236152cf103b34b98bb0dfef56e6042acd0418219a6683a4278b21814b531175825a0b91502d93c0edf80da9e7293bf1ec1b548e679c46d881ac94586396d10c403afbf8bf651289579f1d2a7f71974f185f34aa56e77a04b731bc1cb35ab5ed9da6a8dcfefdd1702b361f90d7761192364ecd508080e4187fdba20161da6d2127a03a0272f8afa2018b33e2e3eae3a5a7c1a075d6
          - name: JWT_ACCESS_EXPIRE_IN
            value: 3600s
          - name: JWT_REFRESH_SECRET
            value: fe9ece88390f2c49168192ecaf165545546fdaba0c6e9cd4aec9569fe6363ba2566277e8cf1b8f3883f7569d7989a25e63e87e3b7f5190869b0abf702a44aa264891c95366bbd7f45602d2aeb230e34b16fff5c0a9782075902f346c229214d9441268617ba41659e1d5515cabf33ed167fc9b330781d5a24e414
          - name: JWT_REFRESH_EXPIRE_IN
            value: 7d
          - name: AES_SECRET_KEY
            value: reaA83IxG8fMkKohU69cVioc
          - name: AUTH_SERVICE_URL
            value: auth-service:80
          - name: VIDEO_SERVICE_URL
            value: video-service:80
          - name: NODE_ENV
            value: production
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  annotations:
    prometheus/scrape: "true"
    prometheus/path: "/metrics"
    prometheus/port: "8080"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-gateway

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-deployment
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 10
        periodSeconds: 3
      selectPolicy: Max
