{
 "title": "DevTube",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace='default'}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory % HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{metric_name='memory', metric_target_type='utilization'} / kube_horizontalpodautoscaler_spec_target_metric{metric_name='memory', metric_target_type='utilization'} * 100",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "CPU Percent HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{metric_name='cpu', metric_target_type='utilization'} / kube_horizontalpodautoscaler_spec_target_metric{metric_name='cpu', metric_target_type='utilization'} * 100",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "K6 LoadTest Duration P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "k6_http_req_duration_p99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "K6 total Request (load test)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "k6_http_reqs_total", "legendFormat": "__auto" }
   ]
  }
 ]
}