# This file is part of the API Gateway project.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: public.ecr.aws/s0p6q3j7/api-gateway:v0.0.1-beta-3-bc9dfa7
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_URL
          value: amqp://user:password@rabbitmq:5672
        - name: DUMMY_RELOAD
          value: 1
