---
apiVersion: v1
kind: Namespace
metadata:
  name: devtube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devtube
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
    spec:
      containers:
      - image: public.ecr.aws/s0p6q3j7/api-gateway:v0.0.4-76ad641
        imagePullPolicy: Always
        name: api-gateway
        ports:
        - containerPort: 8080
        env:
          - name: AUTH_SERVICE_URL
            value: http://auth-service:80
          - name: VIDEO_SERVICE_URL
            value: http://video-service:80
          - name: DATABASE_URL
            value: postgres://postgres:Mayhabuoi123@database-1.cdqce6siqwx7.ap-southeast-1.rds.amazonaws.com:5432/devtube
---
apiVersion: v1
kind: Service
metadata:
  namespace: devtube
  name: api-gateway-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: api-gateway